import type { AppProps } from 'next/app'
import { Provider as ReduxProvider } from 'react-redux'
import { store } from '@/lib/redux/store'
import Head from 'next/head'
import Nav from '@/components/Nav'
import '@/styles/globals.css'

const App = ({ Component, pageProps }: AppProps) => {
    return (
        <>
            <Head>
                <title>ArA Cycling Clothing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ReduxProvider store={store}>
                <Nav />
                <Component {...pageProps} />
            </ReduxProvider>
        </>
    )
}

export default App
